/*!CK:2306272819!*//*1418639315,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["U2j+o"]); }

__d("XUIDialogConfirmButton.react",["React","XUIDialogButton.react","fbt"],function(a,b,c,d,e,f,g,h,i){var j=g.createClass({displayName:"XUIDialogConfirmButton",render:function(){return (g.createElement(h,g.__spread({},this.props,{action:"confirm",label:"Confirm"})));}});e.exports=j;},null);
__d("VitalsEventType",[],function(a,b,c,d,e,f){var g={ASYNC:'event_async',CUSTOM:'event_custom',isValid:function(h){return (h==g.ASYNC||h==g.CUSTOM);}};e.exports=g;},null);
__d("VitalsSession",["WebStorage","md5","sprintf"],function(a,b,c,d,e,f,g,h,i){var j={};function k(l){"use strict";this.appID=l;this.storage=g.getSessionStorage();if(!this.storage){if(!window.__vitals)window.__vitals={};if(!window.__vitals.VitalsSession)window.__vitals.VitalsSession={};this.storage=window.__vitals.VitalsSession;}}k.prototype.getID=function(){"use strict";if(!this.get('id')){var l=i('%s_%s_%s_%s',Date.now(),window.location.href,this.appID,Math.random.toString());this.set('id',h(l));}return this.get('id');};k.prototype.get=function(l){"use strict";return this.storage[this.getFlattenedKey(l)];};k.prototype.set=function(l,m){"use strict";this.storage[this.getFlattenedKey(l)]=m;};k.prototype.getFlattenedKey=function(l){"use strict";return i('%s_%s',this.appID,l);};k.getSession=function(l){if(!j[l])j[l]=new k(l);return j[l];};e.exports=k;},null);
__d("VitalsLogger",["Banzai","VitalsSession","copyProperties","pageID"],function(a,b,c,d,e,f,g,h,i,j){var k={getCategory:function(){return 'vitals';},isEnabled:function(){return g.isEnabled(this.getCategory());},record:function(l,m){if(!this.isEnabled())return;var n=h.getSession(l),o=i({},{apps:[l],page_id:j,session_id:n.getID(),client_time:Date.now(),sensor_data:{}},m);g.post(this.getCategory(),o);}};e.exports=k;},null);
__d("VitalsMode",[],function(a,b,c,d,e,f){var g={MONITOR:0,LOG:1};e.exports=g;},null);
__d("VitalsSensor",["VitalsLogger","VitalsMode","VitalsSession"],function(a,b,c,d,e,f,g,h,i){function j(k,l){"use strict";if(typeof(l)=='undefined'){this.mode=h.MONITOR;}else this.mode=l;this.appID=k;this.initialize();}j.prototype.getAppID=function(){"use strict";return this.appID;};j.prototype.getSession=function(){"use strict";return i.getSession(this.appID);};j.prototype.initialize=function(){"use strict";if(!g.isEnabled())return;if(this.isAllowedOnlyOncePerSession()){if(this.getSession().get(this.getName()))return;this.getSession().set(this.getName(),true);}this.run();};j.prototype.isAllowedOnlyOncePerSession=function(){"use strict";return false;};j.prototype.isMonitorMode=function(){"use strict";return this.mode==h.MONITOR;};j.prototype.isLogMode=function(){"use strict";return this.mode==h.LOG;};j.prototype.getName=function(){"use strict";throw Error("getName() must be implemented for VitalsSensor subclasses!");};j.prototype.run=function(){"use strict";throw Error("run() must be implemented for VitalsSensor subclasses!");};e.exports=j;},null);
__d("VitalsClientSensor",["VitalsLogger","VitalsSensor"],function(a,b,c,d,e,f,g,h){for(var i in h)if(h.hasOwnProperty(i))k[i]=h[i];var j=h===null?null:h.prototype;k.prototype=Object.create(j);k.prototype.constructor=k;k.__superConstructor__=h;function k(){"use strict";if(h!==null)h.apply(this,arguments);}k.prototype.isAllowedOnlyOncePerSession=function(){"use strict";return true;};k.prototype.getName=function(){"use strict";return 'client';};k.prototype.run=function(){"use strict";g.record(this.getAppID(),{sensor:this.getName(),client_time:Date.now(),sensor_data:{user_agent:l(),language:m(),viewport_width:n(),viewport_height:o(),viewport_size:p()}});};var l=function(){return window.navigator.userAgent;},m=function(){return window.navigator.userLanguage||window.navigator.language;},n=function(){return document.documentElement.clientWidth;},o=function(){return document.documentElement.clientHeight;},p=function(){return n()+'x'+o();};e.exports=k;},null);
__d("VitalsContextSensor",["Run","VitalsLogger","VitalsSensor"],function(a,b,c,d,e,f,g,h,i){for(var j in i)if(i.hasOwnProperty(j))l[j]=i[j];var k=i===null?null:i.prototype;l.prototype=Object.create(k);l.prototype.constructor=l;l.__superConstructor__=i;function l(){"use strict";if(i!==null)i.apply(this,arguments);}l.prototype.getName=function(){"use strict";return 'context';};l.prototype.run=function(){"use strict";g.onBeforeUnload(function(){this.shutdown();}.bind(this));};l.prototype.shutdown=function(){"use strict";var event={sensor:this.getName(),client_time:Date.now(),sensor_data:{url:window.location.href,enter:Date.now(),exit:Date.now()}};if(window.__vitals&&window.__vitals.VitalsContextSensor)event.sensor_data.enter=window.__vitals.VitalsContextSensor.enter;h.record(this.getAppID(),event);};e.exports=l;},null);
__d("VitalsReferrerSensor",["VitalsLogger","VitalsSensor"],function(a,b,c,d,e,f,g,h){for(var i in h)if(h.hasOwnProperty(i))k[i]=h[i];var j=h===null?null:h.prototype;k.prototype=Object.create(j);k.prototype.constructor=k;k.__superConstructor__=h;function k(){"use strict";if(h!==null)h.apply(this,arguments);}k.prototype.isAllowedOnlyOncePerSession=function(){"use strict";return true;};k.prototype.getName=function(){"use strict";return 'referrer';};k.prototype.run=function(){"use strict";var l=document.referrer;if(this.isLogMode())l=window.location.href;g.record(this.getAppID(),{sensor:this.getName(),client_time:Date.now(),sensor_data:{referrer:l}});};e.exports=k;},null);
__d("VitalsUserSensor",["VitalsLogger","VitalsSensor"],function(a,b,c,d,e,f,g,h){for(var i in h)if(h.hasOwnProperty(i))k[i]=h[i];var j=h===null?null:h.prototype;k.prototype=Object.create(j);k.prototype.constructor=k;k.__superConstructor__=h;function k(){"use strict";if(h!==null)h.apply(this,arguments);}k.prototype.isAllowedOnlyOncePerSession=function(){"use strict";return true;};k.prototype.getName=function(){"use strict";return 'user';};k.prototype.run=function(){"use strict";g.record(this.getAppID(),{sensor:this.getName(),client_time:Date.now()});};e.exports=k;},null);
__d("Vitals",["VitalsEventType","VitalsLogger","VitalsMode","VitalsClientSensor","VitalsContextSensor","VitalsReferrerSensor","VitalsUserSensor"],function(a,b,c,d,e,f,g,h,i,j,k,l,m){var n={monitor:function(o){if(!h.isEnabled())return;new j(o,i.MONITOR);new k(o,i.MONITOR);new l(o,i.MONITOR);new m(o,i.MONITOR);},log:function(o,event,p){if(!h.isEnabled())return;if(!p)p=g.CUSTOM;if(!g.isValid(p))return;new j(o,i.LOG);new l(o,i.LOG);new m(o,i.LOG);h.record(o,{client_time:Date.now(),sensor:p,sensor_data:{event:event}});}};e.exports=n;},null);
__d("DevsiteVitals",["DOMQuery","Event","Parent","Vitals","csx"],function(a,b,c,d,e,f,g,h,i,j,k){var l={closeDialogMonitor:function(m,n,o){m.subscribe('hide',function(){j.log(n,o);});},addedItemsMonitor:function(m,n,o){h.listen(n,'mouseup',function(p){var q=g.scry(m,"._5rfx"),r='';for(var s=0;s<q.length;s++)if(q[s].firstChild.checked){var t=i.byAttribute(q[s],'data-vitals');if(t)r+=t.getAttribute('data-vitals')+' , ';}j.log(o,r);});},checkBoxMonitor:function(m,n){h.listen(m,'mouseup',function(o){var p=o.getTarget(),q=i.byAttribute(p,'data-vitals');if(q){var r=g.scry(q,"._5rfx");if(r){var s=r[0].firstChild.checked?0:1,event=q.getAttribute('data-vitals')+': '+s;j.log(n,event);}}});},linkButtonSearcher:function(event){return (i.byTag(event.getTarget(),'A')||i.byTag(event.getTarget(),'Button'));},logVitalsAttribute:function(m,n){var o=i.byAttribute(m,'data-vitals');if(!o)return;j.log(n,o.getAttribute('data-vitals'));},logevent:function(m){h.listen(document,'mouseup',function(n){var o=n.getTarget();switch(o.nodeName){case 'A':l.logVitalsAttribute(o,m);break;case 'BUTTON':l.logVitalsAttribute(o,m);break;default:var p=l.linkButtonSearcher(n);if(p)l.logVitalsAttribute(p,m);break;}});}};e.exports=l;},null);
__d("XDeveloperAppControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/apps\/{app_id}\/{?page}\/{?tab}\/{?id}\/",{app_id:{type:"Int",required:true},page:{type:"Enum"},tab:{type:"String"},id:{type:"Int"}});},null);
__d("XDeveloperAppCreateAsyncDialogControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/apps\/async\/create\/dialog\/",{__asyncDialog:{type:"Int"}});},null);